mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.index, name='index'),
    path('home/<str:name>', views.home, name='home'),
    path('home/', views.index, name='home2'),
    path('list_tasks/', views.list_tasks, name='list_tasks'),
    path('list_tasks/infos/<int:id>', views.infos_task, name='infos_task'),
    path('create_task/', views.create_task, name='create_task'),
    path('delete_task/<int:id>', views.delete_task, name='delete_task'),
]

mysite/polls/models.py
import datetime
from typing import Any
from django.db import models
from django.utils.html import format_html
from django.core.exceptions import ValidationError

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    created_date = models.DateField(auto_now_add=True)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return self.name + " - " + self.description
    
    def colored_id(self):
        if self.id % 2:
            color = 'green'
        else:
            color = 'red'
        return format_html(
            '<span style="background-color: {};">{} - {}</span>',
            color,
            self.id,
            self.name
        )
    
    colored_id.allow_tags = True

class TaskForm(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    created_date = models.DateField(auto_now_add=True)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return self.name + " - " + self.description

    def clean(self):
        if self.name == self.description:
            raise ValidationError('Name and description must be different')
        if self.created_date > datetime.date.today():
            raise ValidationError('Created date must be in the past')
        if self.closed and self.created_date == datetime.date.today():
            raise ValidationError('Closed tasks cannot be created today')
        if self.closed and self.created_date > datetime.date.today():
            raise ValidationError('Closed tasks cannot be created in the future')
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super(Task, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.full_clean()
        super(Task, self).delete(*args, **kwargs)

mysite/polls/views.py
import datetime
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Task

# Create your views here.
def index(request):
    return HttpResponse("<h1> Hello, world.</h1> <br> You're at the polls index.")

def home(request, name):
    return HttpResponse("<h1> Hello,"+ name +".</h1> <br> You're at the "+ name +"'s home.")

def list_tasks(request):
    tasks = Task.objects.all()
    return render(request, 'list_tasks.html', {'tasks': tasks})

def infos_task(request, id):
    # task = Task.get_objects.get(id=id)
    task = get_object_or_404(Task, pk=id)
    return render(request, 'infos_task.html', {'task': task})

def create_task(request):
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        task = Task(name=name, description=description)
        task.save()
        return HttpResponseRedirect(reverse('polls:list_tasks'))
    else:
        return render(request, 'create_task.html')

def delete_task(request, id):
    task = get_object_or_404(Task, pk=id)
    task.delete()
    return HttpResponseRedirect(reverse('polls:list_tasks'))

mysite/polls/templates/base_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body class="bg-dark">
    <header class="bg-dark">
        <h1 class="text-info">Gestion des taches</h1>
    </header>

    <section >
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>

mysite/polls/templates/create_task.html
{% extends 'base_layout.html' %}
{% block title %} Formulaire de tache {% endblock %}
{% block content %}
    <h2 class="text-info m-2">Créer une tache</h2>
    <form action="{% url 'polls:create_task' %}" method="post">
        {% csrf_token %}
        <label class="text-white m-2" for="name">Nom</label>
        <input class=" bg-dark border border-2 border-info rounded m-2 text-white" type="text" name="name" id="name" required>
        <br>
        <label class="text-white m-2" for="description">Description</label>
        <input class=" bg-dark border border-2 border-info rounded m-2 text-white" type="text" name="description" id="description" required>
        <br>
        <input class="btn btn-primary m-2" type="submit" value="Créer">
    </form>
    <br>
    <a class="btn btn-danger m-2" id="button-back" href="{% url 'polls:list_tasks' %}">Retour</a>
{% endblock %}

mysite/polls/templates/infos_task.html
{% extends 'base_layout.html' %}
{% block title %} Informations taches {% endblock %}
{% block content %}
<h3 class="text-info m-2">Informations tache</h3>
    {% if task %}
        <h5 class="text-white m-2">Nom : <p class="text-info m-2">{{ task.name }}.</p></h5>
        <h5 class="text-white m-2">Description : <p class="text-info m-2">{{ task.description }}</p></h5>
        <h5 class="text-white m-2">Date de création : <p class="text-info m-2">{{ task.created_date }}.</p></h5>
        <h5 class="text-white m-2">Fermé : <p class="text-info m-2">{{ task.closed }}</p></h5>
    {% else %}
        <p class="text-info m-2">Vous n'avez aucune tâche en cours</p>
    {% endif %}
    <br>
    <a class="btn btn-danger m-2" id="button-back" href="{% url 'polls:list_tasks' %}">Retour</a>
{% endblock %}

mysite/polls/templates/list_tasks.html
{% extends 'base_layout.html' %}
{% block title %}
  Liste des taches
{% endblock %}
{% block content %}
  <h3 class="text-info m-2">Ma liste de tache</h3>
  {% if tasks %}
    <p class="text-white m-2">Vous avez {{ tasks|length }} tâches en cours</p>
    <table class="bg-info rounded-3 border border-2 d-flex flex-column m-2" style="max-width: max-content;">
      <thead align="center">
        <tr>
          <th class="text-white p-2" colspan="4">Liste des taches</th>
        </tr>
      </thead>
      <tbody align="center">
        <th class="text-dark">Nom</th>
        <th class="text-dark">Description</th>
        <th class="text-dark">Informations</th>
        <th class="text-dark">Supprimer</th>
        {% for task in tasks %}
          <tr align="center">
            <td class="text-dark p-1">{{ task.name }}</td>
            <td class="text-dark p-1">{{ task.description }}</td>
            <td class="p-1">
              <a class="btn btn-primary" id="button-back" href="{% url 'polls:infos_task' task.id %}">Details</a>
            </td>
            <td class="p-1">
              <a class="btn btn-danger" id="button-back" href="{% url 'polls:delete_task' task.id %}">Supprimer</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Vous n'avez aucune tâche en cours</p>
  {% endif %}
  <a class="btn btn-primary p-2 m-2" id="button-back" href="{% url 'polls:create_task' %}">Créer tache</a>
{% endblock %}